spring.application.name=backend

# Conexao PostgreSQL na Nuvem (Neon)
spring.datasource.url=jdbc:postgresql://ep-aged-frost-acjim8h9-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Iacym1vfjtV4
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl